// 84 ISAAC_CHARACTERS — ordered: 17 base characters, 17 Tainted variants, 50 familiars.
// Order matters: the WHO AM I? picker shows characters first, then familiars.
// Derived from sprite-sources/manifest.json. Do not edit by hand.
export const ISAAC_CHARACTERS: readonly string[] = [
  // — character —
  "apollyon",
  "azazel",
  "bethany",
  "blue-baby",
  "cain",
  "eden",
  "eve",
  "isaac",
  "jacob-and-esau",
  "judas",
  "keeper",
  "lazarus",
  "lilith",
  "magdalene",
  "samson",
  "the-forgotten",
  "the-lost",
  // — tainted —
  "tainted-apollyon",
  "tainted-azazel",
  "tainted-bethany",
  "tainted-blue-baby",
  "tainted-cain",
  "tainted-eden",
  "tainted-eve",
  "tainted-forgotten",
  "tainted-isaac",
  "tainted-jacob",
  "tainted-judas",
  "tainted-keeper",
  "tainted-lazarus",
  "tainted-lilith",
  "tainted-lost",
  "tainted-magdalene",
  "tainted-samson",
  // — familiar —
  "abel",
  "acid-baby",
  "bbf",
  "best-bud",
  "big-chubby",
  "big-fan",
  "bloodshot-eye",
  "brother-bobby",
  "bumbo",
  "charged-baby",
  "cube-baby",
  "cube-of-meat",
  "daddy-longlegs",
  "dark-bum",
  "dead-bird",
  "dead-cat",
  "demon-baby",
  "distant-admiration",
  "dry-baby",
  "ghost-baby",
  "guardian-angel",
  "halo-of-flies",
  "harlequin-baby",
  "headless-baby",
  "holy-water",
  "incubus",
  "king-baby",
  "leech",
  "lil-abaddon",
  "lil-brimstone",
  "lil-delirium",
  "lil-haunt",
  "lil-loki",
  "lil-monstro",
  "little-steven",
  "lost-soul",
  "papa-fly",
  "psy-fly",
  "punching-bag",
  "rainbow-baby",
  "robo-baby",
  "robo-baby-2",
  "rotten-baby",
  "sacrificial-dagger",
  "seraphim",
  "sister-maggy",
  "sprinkler",
  "succubus",
  "sworn-protector",
  "vanishing-twin",
] as const;

export type IsaacCharacterId = typeof ISAAC_CHARACTERS[number];
