// Package core contains the canonical business logic for pokegents:
// state machine, session identity resolution, and shared types.
package core

// SessionState represents the state of an agent in the state machine.
type SessionState string

const (
	StateIdle       SessionState = "idle"
	StateBusy       SessionState = "busy"
	StateNeedsInput SessionState = "needs_input"
	StateError      SessionState = "error"
)

// IsActive returns true if the agent is doing work or waiting for input.
func (s SessionState) IsActive() bool {
	return s == StateBusy || s == StateNeedsInput
}

// CanInterrupt returns true if a tool event (PreToolUse/PostToolUse) is
// allowed to set the state. Only busy and needs_input can be overwritten
// by tool events — error/idle require UserPromptSubmit to transition.
func (s SessionState) CanInterrupt() bool {
	return s == StateBusy || s == StateNeedsInput || s == ""
}

// HookEvent is the JSON payload from Claude Code lifecycle hooks.
// Received via HTTP POST from dashboard-notify.sh or via the hook input pipe.
type HookEvent struct {
	SessionID            string `json:"session_id"`
	HookEventName        string `json:"hook_event_name"`
	ToolName             string `json:"tool_name,omitempty"`
	ToolInput            any    `json:"tool_input,omitempty"`
	CWD                  string `json:"cwd"`
	LastAssistantMessage string `json:"last_assistant_message,omitempty"`
	NotificationType     string `json:"notification_type,omitempty"`
	TranscriptPath       string `json:"transcript_path,omitempty"`
	Prompt               string `json:"prompt,omitempty"`
}

// SessionIdentity holds the multiple IDs that identify an agent session.
// See CLAUDE.md "Session Identity" for why there are three IDs.
type SessionIdentity struct {
	// SessionID is Claude's conversation session ID (assigned by Claude, may change on resume).
	SessionID string
	// RunID is the stable unique agent ID generated by boa.sh.
	RunID string
	// ProfileName is the profile this session was launched from.
	ProfileName string
	// TTY is the terminal device (e.g. /dev/ttys001).
	TTY string
	// ITermSessionID is the iTerm2 session UUID (stable across tab moves).
	ITermSessionID string
}

// --- Data types (shared across store, services, and server) ---

// AgentIdentity is the persistent identity for an agent, stored in ~/.the-binding-of-agents/agents/{pokegent_id}.json.
// Unlike RunningSession (ephemeral, deleted on exit), identity files are never deleted automatically.
type AgentIdentity struct {
	RunID       string `json:"run_id"`
	DisplayName string `json:"display_name"`
	Sprite      string `json:"sprite,omitempty"`
	Role        string `json:"role,omitempty"`
	Project     string `json:"project,omitempty"`
	Profile     string `json:"profile,omitempty"`
	TaskGroup   string `json:"task_group,omitempty"`
	Model       string `json:"model,omitempty"`
	Effort      string `json:"effort,omitempty"`
	CreatedAt   string `json:"created_at,omitempty"`
	// Interface is the runtime backend bound to this agent: "" / "iterm2" =
	// Claude Code in a terminal tab; "chat" = ACP-backed embedded panel.
	// Set at launch time, survives session resume.
	Interface string `json:"interface,omitempty"`
	// AgentBackend is the configured chat backend key, e.g. "claude" or
	// "codex". It is needed to revive chat agents from the PC box.
	AgentBackend string `json:"agent_backend,omitempty"`
}

// RunningSession is the data stored in ~/.the-binding-of-agents/running/*.json.
type RunningSession struct {
	Profile        string `json:"profile"`
	SessionID      string `json:"session_id"`
	PID            int    `json:"pid"`
	ClaudePID      int    `json:"claude_pid"`
	TTY            string `json:"tty"`
	DisplayName    string `json:"display_name"`
	RunID          string `json:"run_id,omitempty"`
	ITermSessionID string `json:"iterm_session_id,omitempty"`
	CreatedAt      string `json:"created_at,omitempty"`
	Role           string `json:"role,omitempty"`            // role name (empty for legacy/bare project)
	Project        string `json:"project,omitempty"`         // project name (empty for legacy profiles)
	TaskGroup      string `json:"task_group,omitempty"`      // organizational grouping (e.g. "proxy", "auth-migration")
	Model          string `json:"model,omitempty"`           // provider model id (legacy aliases accepted on migration)
	Effort         string `json:"effort,omitempty"`          // reasoning effort level (low, medium, high, max)
	Sprite         string `json:"sprite,omitempty"`          // avatar sprite name (single source of truth)
	Interface      string `json:"interface,omitempty"`       // "" / "iterm2" or "chat" — runtime backend
	AgentBackend   string `json:"agent_backend,omitempty"`   // ACP backend type: "claude-acp", "codex-acp", "codex"
	CWD            string `json:"cwd,omitempty"`             // working directory (persisted for non-Claude reattach)
	TranscriptPath string `json:"transcript_path,omitempty"` // explicit transcript path (for non-Claude backends)
	// LastGood* preserves the most recent verified native transcript/session
	// pair. Chat ACP restarts may produce a transient session_id before a
	// transcript exists; revive/reattach should fall back to this pair instead
	// of overwriting durable history with an unverified backend session.
	LastGoodSessionID      string `json:"last_good_session_id,omitempty"`
	LastGoodTranscriptPath string `json:"last_good_transcript_path,omitempty"`
	// SourceTranscriptPath preserves the pre-migration transcript when a chat
	// agent switches backends (for example Claude → Codex). Non-Claude ACP
	// backends cannot load Claude's session directly, so relaunch uses this
	// path to inject prior conversation context into the new backend.
	SourceTranscriptPath string `json:"source_transcript_path,omitempty"`
}

// Agent interface implementation for identity resolution.
func (rs *RunningSession) GetSessionID() string   { return rs.SessionID }
func (rs *RunningSession) GetRunID() string       { return rs.RunID }
func (rs *RunningSession) GetDisplayName() string { return rs.DisplayName }
func (rs *RunningSession) GetTTY() string         { return rs.TTY }

// StatusFile is the data stored in ~/.the-binding-of-agents/status/*.json.
type StatusFile struct {
	FileKey       string   `json:"-"` // filename base (pokegent_id), not serialized
	SessionID     string   `json:"session_id"`
	State         string   `json:"state"`
	Detail        string   `json:"detail"`
	CWD           string   `json:"cwd"`
	Timestamp     string   `json:"timestamp"`
	BusySince     string   `json:"busy_since,omitempty"`
	LastSummary   string   `json:"last_summary"`
	LastTrace     string   `json:"last_trace"`
	UserPrompt    string   `json:"user_prompt"`
	RecentActions []string `json:"recent_actions,omitempty"`
	ContextTokens int      `json:"context_tokens,omitempty"`
	ContextWindow int      `json:"context_window,omitempty"`
}

// Profile represents a pokegent profile configuration.
type Profile struct {
	Name         string `json:"name"`
	Title        string `json:"title"`
	Emoji        string `json:"emoji"`
	Color        [3]int `json:"color"`
	CWD          string `json:"cwd"`
	SystemPrompt string `json:"system_prompt,omitempty"`
	ITermProfile string `json:"iterm2_profile,omitempty"`
	Model        string `json:"model,omitempty"`
	Effort       string `json:"effort,omitempty"`
}

// AppConfig is the global config from ~/.the-binding-of-agents/config.json.
type AppConfig struct {
	Port                int    `json:"port"`
	DefaultProfile      string `json:"default_profile"`
	DefaultProject      string `json:"default_project,omitempty"`
	DefaultRole         string `json:"default_role,omitempty"`
	SkipPermissions     bool   `json:"skip_permissions"`
	ITermRestoreProfile string `json:"iterm2_restore_profile"`
}

// ProjectConfig defines a workspace — where the agent works.
// Stored in ~/.the-binding-of-agents/projects/*.json.
type ProjectConfig struct {
	Name          string   `json:"name"`
	Title         string   `json:"title"`
	Color         [3]int   `json:"color"`
	CWD           string   `json:"cwd"`
	AddDirs       []string `json:"add_dirs,omitempty"`
	ContextPrompt string   `json:"context_prompt,omitempty"`
	ITermProfile  string   `json:"iterm2_profile,omitempty"`
	Model         string   `json:"model,omitempty"`
	Effort        string   `json:"effort,omitempty"`
}

// RoleConfig defines a persona — how the agent behaves.
// Stored in ~/.the-binding-of-agents/roles/*.json.
type RoleConfig struct {
	Name            string `json:"name"`
	Title           string `json:"title"`
	Emoji           string `json:"emoji"`
	SystemPrompt    string `json:"system_prompt"`
	SkipPermissions *bool  `json:"skip_permissions,omitempty"` // nil = inherit from config
	Model           string `json:"model,omitempty"`
	Effort          string `json:"effort,omitempty"`
}

// EphemeralAgent represents a Claude Code built-in Agent tool subagent
// tracked for dashboard visibility. Stored in ~/.the-binding-of-agents/ephemeral/*.json.
type EphemeralAgent struct {
	AgentID         string `json:"agent_id"`              // unique ID from SubagentStart hook
	AgentType       string `json:"agent_type"`            // Explore, Plan, general-purpose, etc.
	ParentSessionID string `json:"parent_session_id"`     // pokegent ID of spawning agent
	Description     string `json:"description,omitempty"` // short task description
	Prompt          string `json:"prompt,omitempty"`      // task prompt (truncated)
	State           string `json:"state"`                 // "running" or "completed"
	CWD             string `json:"cwd,omitempty"`
	CreatedAt       string `json:"created_at"`
	CompletedAt     string `json:"completed_at,omitempty"`
	LastMessage     string `json:"last_message,omitempty"` // final result summary
	TranscriptPath  string `json:"transcript_path,omitempty"`
	DurationSec     int    `json:"duration_sec,omitempty"`
}

// Message represents a message between agents.
type Message struct {
	ID        string `json:"id"`
	From      string `json:"from"`
	FromName  string `json:"from_name"`
	To        string `json:"to"`
	ToName    string `json:"to_name"`
	Content   string `json:"content"`
	Timestamp string `json:"timestamp"`
	Delivered bool   `json:"delivered"`
}

// Connection represents a communication link between two agents.
type Connection struct {
	AgentA       string `json:"agent_a"`
	AgentB       string `json:"agent_b"`
	AgentAName   string `json:"agent_a_name"`
	AgentBName   string `json:"agent_b_name"`
	MessageCount int    `json:"message_count"`
	LastMessage  string `json:"last_message"`
}

// ActivityEntry is a single line in the activity log.
type ActivityEntry struct {
	Timestamp string `json:"timestamp"`
	SessionID string `json:"session_id"`
	AgentName string `json:"agent_name"`
	Files     string `json:"files"`
	Summary   string `json:"summary"`
	Raw       string `json:"-"`
}

// FileEvent represents a change to a watched file.
type FileEvent struct {
	Type      string // "create", "update", "delete", "rename"
	SessionID string
	Path      string
}

// --- State machine result ---

// StateTransitionResult is returned by ApplyEvent with the new state and metadata.
type StateTransitionResult struct {
	// NewState is the resulting state after the event.
	NewState SessionState
	// Skip is true if the event should be ignored (e.g. clone SessionStart on busy agent).
	Skip bool
	// Detail is the human-readable status detail.
	Detail string
	// Summary is the last assistant message (set on Stop).
	Summary string
	// BusySince is the timestamp when the agent became busy (set on UserPromptSubmit).
	BusySince string
	// ClearActions is true if recent_actions should be reset.
	ClearActions bool
	// ToolAction is the action string to append to recent_actions (if non-empty).
	ToolAction string
}
